---
title: "**Informe Estadístico**"
subtitle: "Estadística Básica"
author: "Pontificia Universidad Javeriana Cali"
date: "2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
# Colores - paleta de azules
c1="#001A33"
c2="#003366"
c3="#004080"
c4="#1A8CFF"
c5="#4DA6FF"
c6="#80BFFF"
c7="#B3D9FF"

# <span style="color:#001A33"> 

## <span style="color:#003366">  

### <span style="color:#004080">
### <span style="color:#1A8CFF">
### <span style="color:#4DA6FF">
### <span style="color:#80BFFF">
### <span style="color:#B3D9FF">

# Cargar la librería ggplot2
library(ggplot2)

# Generar datos continuos
set.seed(123)  # Para que los datos generados sean reproducibles
datos <- rnorm(30, mean = 42, sd = 6)
#round(datos,0)

library(paqueteMODELOS)
data(creditos)
id = sample(1:780, 200, replace = FALSE)
credit = creditos[id,]
```


<br/>

Despues de haber desarrollado todos los pasos de un estudio estadístico es necesario presentar los resultados obtenidos mediante un **Informe Final**, que esencialmente contiene los hallazgos más importantes, las conclusiones y recomendaciones.

<br/>

Los informes estadísticos suelen tener una estructura similar, que incluye las siguientes partes:

<br/>

* **Introducción**: En esta parte se presenta el tema del informe, los objetivos del estudio y la metodología utilizada.

<br/>

* **Presentación de datos**: En esta parte se presentan los datos recopilados, en forma de tablas, gráficos o diagramas.

<br/>

* **Análisis de datos**: En esta parte se analiza los datos presentados, para identificar tendencias, patrones y relaciones.

<br/>

* **Conclusiones y recomendaciones**: En esta parte se resumen los principales hallazgos del estudio y posibles trabajos futuros derivados del cono

<br/>

* **Anexos**: Ademas de los puntos anteriores se destinan unos apartados con información adicional como tablas e información especifica 

En esta parte se pueden incluir:

<br/>

  * **Datos brutos**: Los datos brutos son los datos originales que se recopilaron para el informe. Los datos brutos pueden ser útiles para los lectores que desean realizar su propio análisis.

  * **Tablas adicionales**: Las tablas adicionales pueden proporcionar información adicional sobre los datos presentados en el informe principal.

  * **Gráficos adicionales**: Los gráficos adicionales pueden proporcionar una visualización adicional de los datos presentados en el informe principal.

  * **Fórmulas**: Las fórmulas pueden proporcionar información sobre cómo se calcularon los resultados presentados en el informe principal.

  * **Información metodológica**: La información metodológica puede proporcionar información sobre cómo se recopilaron y analizaron los datos.


<br/><br/>

### **Recomendaciones**


* Identificar al lector del informe y adptar la terminología para su facil compresión

* Cosiderar si los lectores tienen comocimientos estadísticos con el fin de explicar o no conceptos en detalle que ayuden al entendimiento del documento.

* Organizar el informe de forma lógica con introducción, metodología, resultados discusión y conclusiones

* Utilizar gráficos y tablas para presentar los resultados de forma que facilite su interpretación.

* Utilizar referencias bibliograficas que soporten la metodología utilizada

* Utilizar un formato con normas como APA o MLA

* Considerar las implicaciones eticas y de provacidad de los datos que se están utilizando 

