---
title: <span style="color:#004080">**Tablas de frecuencia**</span>
subtitle: "Estadística Básica"
author: "Pontificia Universidad Javeriana Cali"
date: "2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Colores - paleta de azules
c1="#001A33"
c2="#003366"
c3="#004080"
c4="#1A8CFF"
c5="#4DA6FF"
c6="#80BFFF"
c7="#B3D9FF"

# <span style="color:#001A33"> 

## <span style="color:#003366">  

### <span style="color:#004080">
### <span style="color:#1A8CFF">
### <span style="color:#4DA6FF">
### <span style="color:#80BFFF">
### <span style="color:#B3D9FF">

```

<br><br><br><br>

Una tabla de frecuencias es una forma de resumir datos estadísticos cualitativos o categóricos. Proporciona una descripción resumida de la distribución de frecuencias de diferentes categorías en un conjunto de datos. Las tablas de frecuencias son útiles para visualizar patrones, identificar tendencias y resaltar características importantes de los datos.

<br><br>

## **Tablas variables nominales**

Presentan tres columnas
* Categorías : opciones o valores distintos que se resumen en la tabla
* Frecuencia absoluta : Número de veces que aparece una categoría o valor específico en los datos
* Frecuencia relativa : Proporción de la frecuencia absoluta de una categoría en relación con el total de datos

<br><br>

### **Ejemplo**

| Tipo de Queja             | Frecuencia  Absoluta  | Frecuencia Relativa  |
|:--------------------------|----------------------:|---------------------:|
| Demora en transacciones   |              	120     |	0.2608696	           |	
| Cobros incorrectos        |	               80	    |  0.1739130	      	 |
| Mala atención al cliente  |	              150	    |  0.3260870	         |
| Problemas en el sitio web |                50	    |  0.1086957		       |
| Otros	                    |                60	    |  0.1304348	         |
|                           |                       |                      |

<br><br>

## **Tablas variables ordinales**

<br><br>

## **Tablas de doble entrada o cruzadas**

<br><br>

## **Recodificación de variables cuantitavas**

<br><br>