---
title: <span style="color:#004080">**Introducción**</span>
subtitle: "Estadística avanzada"
author: "Pontificia Universidad Javeriana Cali"
date: "2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Colores - paleta de azules
c1="#001A33"
c2="#003366"
c3="#004080"
c4="#1A8CFF"
c5="#4DA6FF"
c6="#80BFFF"
c7="#B3D9FF"

# <span style="color:#001A33"> 

## <span style="color:#003366">  

### <span style="color:#004080">
### <span style="color:#1A8CFF">
### <span style="color:#4DA6FF">
### <span style="color:#80BFFF">
### <span style="color:#B3D9FF">

```

<br/><br/>

El análisis de datos multivariante abarca un conjunto de técnicas estadísticas utilizadas para entender las relaciones y dinámicas entre múltiples variables en un conjunto de datos. Estas técnicas son cruciales para explorar datos complejos y encontrar patrones o correlaciones que no serían aparentes con métodos univariados o bivariados.

<br/>

A medida que el volumen y la variedad de datos aumentan, el análisis multivariante se vuelve indispensable en campos como la biología, las finanzas, la sociología y más allá. Estos métodos nos permiten simplificar la complejidad de los datos a través de la reducción de la dimensionalidad, la clasificación y la modelización de relaciones entre variables. Entre sus principales objetivos se tiene :

<br/><br/>

### **1. La  Reducción de Dimensionalidad**

<br/>

Estos métodos se utilizan para simplificar la complejidad de los conjuntos de datos con muchas variables, preservando la mayor parte de la información en un espacio de menor dimensión. (Análisis de Componentes Principales)

<br/><br/>

### **2. La Clasificación y Agrupamiento**

<br/>

Estos métodos buscan identificar estructuras en los datos agrupando objetos en conjuntos que comparten características similares, sin necesidad de etiquetas predefinidas.(Análisis de Conglomerados o Cluster)

<br/><br/>

### **3. La Inferencia y Predicción**

<br/>

Estos métodos se enfocan en modelar las relaciones entre una o más variables independientes y dependientes, principalmente para hacer inferencias o predicciones. (Regresión Linal)

<br/><br/>

### **4. La Exploración de Relaciones Entre Variables**

<br/>

Estos métodos analizan las interacciones o asociaciones entre variables categóricas en conjuntos de datos. (Análisis de Correspondencia)


<br/><br/>





